Save in history incorrect REPL expressions
phel-lang/phel-lang pull request #207
Opened 2021-01-28 17:02 UTC by JesusValera

## 📚 Description

Closes https://github.com/phel-lang/phel-lang/issues/205

When you press `<ENTER>` in the REPL, even if the statement is incorrect, it will be saved inside the `phel-repl-history` file.

## 🖼️  Screenshot

![image](https://user-images.githubusercontent.com/6381924/106172338-02344980-6193-11eb-97bc-6f994177e2af.png)

2021-01-28 17:05 UTC, Chemaclass commented on src/php/Command/ReplCommand.php
> +        if (!empty($input)) {
```suggestion
    private function addHistory(string $input): void
    {
        if ('' !== $input)) {
```

2021-01-28 17:20 UTC, Chemaclass approved these changes
Good one!

2021-01-28 17:46 UTC, jenshaase requested changes
This is not working correctly in multi line mode. If I type this
```
phel:3> (
....:4> +
....:5> 1
....:6> 3
....:7> )
4
phel:8>
```
The history is `(`, `+`, `1`, `3`, `)` and not
```
(
+
1
3
)
```

2021-01-28 17:50 UTC, JesusValera commented
> This is not working correctly in multi line mode. If I type this
> 
> ```
> phel:3> (
> ....:4> +
> ....:5> 1
> ....:6> 3
> ....:7> )
> 4
> phel:8>
> ```
> 
> The history is `(`, `+`, `1`, `3`, `)` and not
> 
> ```
> (
> +
> 1
> 3
> )
> ```

Do you mean, if you press `up`, it should display all those lines in a single one?

2021-01-28 19:52 UTC, jenshaase commented
Not in a single row but like this
```
phel:3> (
....:4> +
....:5> 1
....:6> 3
....:7> )
4
phel:8> (
+
1
3
)
```

That's how it was before.

2021-01-30 12:11 UTC, JesusValera commented
Sorry for the delay.

Basically, I was storing into the `history` line-by-line, the solution was storing just after imploding all the input buffer. 😄 

@jenshaase @Chemaclass

2021-01-30 12:22 UTC, Chemaclass commented
You are storing the inputBuffer every time even when it was Unfinished.  Test this:
1) delete all content from the `.phel-repl-history`
2) exec in repl
```clojure
(defn adder [& xs]
  (apply + xs)
  ]
```
3) the `.phel-repl-history` should have only 1 line

2021-01-30 12:26 UTC, JesusValera commented
> You are storing the inputBuffer every time even when it was Unfinished. Test this:
> 
> 1. delete all content from the `.phel-repl-history`
> 2. exec in repl
> 
> ```clojure
> (defn adder [& xs]
>   (apply + xs)
>   ]
> ```
> 
> 1. the `.phel-repl-history` should have only 1 line

That's true!
Thank you for spotting this bug :P

FIXED!

2021-01-30 12:54 UTC, merged