Adding re-seq phel function
phel-lang/phel-lang pull request #259
Opened 2021-03-22 19:37 UTC by Chemaclass

## 🔖 Changes

Added `re-seq` phel function inside `/core/regex-functions.phel`.

2021-03-24 10:03 UTC, JesusValera approved these changes

2021-04-29 19:36 UTC, jenshaase requested changes

2021-04-29 19:36 UTC, jenshaase commented on src/phel/core/regex-functions.phel
> +    (apply array (php/aget matches 0))))
`(apply vector ...)`

2021-04-29 19:48 UTC, Chemaclass commented on src/phel/core/regex-functions.phel
> +    (apply array (php/aget matches 0))))
Done

2021-05-04 18:57 UTC, jenshaase commented
Can you add a line to Changelog.md that this function was added?

2021-05-04 19:33 UTC, merged