Add contains? phel function
phel-lang/phel-lang pull request #267
Opened 2021-05-02 10:03 UTC by Chemaclass

## 📚 Description

Inspired on https://clojuredocs.org/clojure.core/contains_q
> Returns true if the key is present in the given collection, otherwise returns false.

This PR should solved this issue: https://github.com/phel-lang/phel-lang/issues/252

## 🔖 Changes

- Created `contains?` phel function
- Moved ` nil?` from `type-operation.phel` to `boolean-operation.phel` because its needed on the new one

2021-05-03 11:04 UTC, JesusValera approved these changes

2021-05-05 07:59 UTC, jenshaase requested changes

2021-05-10 20:12 UTC, jenshaase approved these changes

2021-05-11 04:35 UTC, Chemaclass reviewed
Thanks, @jenshaase ✅

2021-05-12 18:22 UTC, merged