Using symfony/console
phel-lang/phel-lang pull request #278
Opened 2021-05-16 21:20 UTC by Chemaclass

## 📚 Description

Using Symfony Command Component for our Commands as well. 

## 🔖 Changes

- Require `symfony/console`
- Extend Symfony Command in the Export, Format, Repl, Run and Test phel commands
- Instantiate the phel commands directly in the phel entry point
- Deleted the unnecessary PhelFacade/PhelFactory code. It's not necessary anymore.

### Follow up

I got some ideas for some other related clean-ups on the commands, but I will apply them in other PR. On this PR I wanted to do the few changes as possible because it would get too big (and out of control) easily. This way it will be easier to see what's going on.

2021-05-16 21:34 UTC, JesusValera approved these changes
When I saw the PR title I was not sure about the idea of including the Symfony dependency in the project.
But now with perspective I find much explicit and understandable the command. 👍🏼👍🏼😀

2021-05-17 11:43 UTC, jenshaase requested changes

2021-05-17 11:43 UTC, jenshaase commented on src/php/Command/Export/ExportCommand.php
>              $this->io->writeStackTrace($e);
`return Command::FAILURE;`

2021-05-17 11:43 UTC, jenshaase commented on src/php/Command/Run/RunCommand.php
>              $this->io->writeLocatedException($e->getNestedException(), $e->getCodeSnippet());
`return Command::FAILURE;`

2021-05-17 11:43 UTC, jenshaase commented on src/php/Command/Run/RunCommand.php
>              $this->io->writeStackTrace($e);
`return Command::FAILURE;`

2021-05-17 11:43 UTC, jenshaase commented on src/php/Command/Run/RunCommand.php
> +        return 0;
`return Command::SUCCESS;`

2021-05-17 11:43 UTC, jenshaase commented on src/php/Command/Repl/ReplCommand.php
> +        return 0;
`return Command::SUCCESS;`

2021-05-17 11:43 UTC, jenshaase commented on src/php/Command/Format/FormatCommand.php
> +        return 0;
`return Command::SUCCESS;`

2021-05-17 11:43 UTC, jenshaase commented on src/php/Command/Export/ExportCommand.php
> +        return 0;
`return Command::SUCCESS;`

2021-05-17 19:16 UTC, jenshaase approved these changes

2021-05-17 19:16 UTC, merged

2021-05-17 19:17 UTC, jenshaase commented
Thanks, I merged it!