Update gacela@0.22
phel-lang/phel-lang pull request #488
Opened 2022-06-11 04:02 UTC by Chemaclass

### 🔖 Changes

- Update to latest gacela version

This version includes a cache system that should improve the performance of gacela class resolving types.

Changelog: https://github.com/gacela-project/gacela/releases/tag/0.22.0

2022-06-11 08:47 UTC, JesusValera approved these changes

2022-06-11 20:06 UTC, JesusValera approved these changes

2022-06-13 18:16 UTC, jenshaase requested changes

2022-06-13 19:20 UTC, Chemaclass commented on composer.json
> +            "find . -type f -name '.gacela*.cache' -exec rm {} \\;"
You're right, no, it's not special to Phel. The idea for this was able to delete all cache files that gacela generates for the test cases in order to have a "clean start", but I guess this is not really a problem or even necessary. I will remove this line.

2022-06-13 19:25 UTC, JesusValera commented on composer.json
> +            "find . -type f -name '.gacela*.cache' -exec rm {} \\;"
@jenshaase @Chemaclass let me check if this line even works with Windows 11 + Linux Subsystem terminal, I think it should 🤔

2022-06-20 20:26 UTC, jenshaase approved these changes

2022-06-20 20:27 UTC, merged